### ISSUE TITLE
formatting JSON documents generates fake XP

### ISSUE THREAD

**Issue by sharpred** [riussi/code-stats-vscode#6]
Juha, I will PM you directly but have been contacted by the admin of code::stats who told me he was getting millions of JSON XP from me he says "I think there is a problem with how the VSCode plugin detects copypastes or edits to bigger regions of text. We will have to see how to fix it." I will fork your repo and see if I can see what is happening

**Comment by sharpred** [comment]
loaded a large JSON file and formatted it, creating over 100,000 XP. Can provide a sample file if needed

**Comment by sharpred** [comment]
PR in

**Comment by riussi** [comment]
PR merged and released in 1.0.7. Thank you for the contribution.
