### ISSUE TITLE
Paste detection misses long lines

### ISSUE THREAD

**Issue by Nicd** [riussi/code-stats-vscode#8]
Currently the copypaste detection relies on checking if there are linebreaks in the text. This does not account for very long lines and they are counted in their entirety.

Unsure how we should proceed with their detection. At the least there should probably be some reasonable limit to how much XP you can get per change event.

**Comment by Nicd** [comment]
It seems VSCode Vim extension uses this to detect typing? https://github.com/VSCodeVim/Vim/blob/eae183596104d820ca2f87a1934d7a03097dd32c/extension.ts#L215

Maybe we could do that too, but it would conflict with the Vim extension.

**Comment by riussi** [comment]
Looking into it...
